### PR TITLE
MULTIARCH-4809: Rebase with upstream: go modules updates and code changes.

### PR DESCRIPTION
**Pull request by kishen-v**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR rebases the fork with the latest upstream. 

Steps:
```
git remote set-url origin git@github.com:openshift/ibm-powervs-block-csi-driver.git
git pull
git checkout -b openshift-mn
git remote add upstream https://github.com/kubernetes-sigs/ibm-powervs-block-csi-driver.git
git fetch upstream
git merge upstream/main
git remote set-url origin git@github.com]://<own-repo>/ibm-powervs-block-csi-driver.git
git push
```
**Release note**:
```
none
```

### CODE REVIEW

**Comment by kishen-v** [comment]
cc @yussufsh  @Karthik-K-N

**Comment by Karthik-K-N** [comment]
Please add the steps used to rebase may help in future

**Comment by yussufsh** [comment]
/hold
We also need to update the k8s version upstream.

**Review by yussufsh — APPROVED** [review]
/lgtm

**Pull request merged**
