### PR TITLE
[release-4.13] Updated golang.org/x/net/html dependency.

### PR DESCRIPTION
**Pull request by yussufsh**
**What type of PR is this?**
/kind cleanup
/kind bug

**What this PR does / why we need it**:
This is cherry-pick for #43 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Review by mkumatag — APPROVED** [review]
/lgtm

**Comment by yussufsh** [comment]
> /jira refresh

JIRA is set for release 4.14. Should I remove the JIRA ref from the title?

**Comment by jaypoulz** [comment]
excellent, thanks!

**Pull request merged**
