### PR TITLE
Rebase with upstream kubernetes-sigs/ibm-powervs-block-csi-driver

### PR DESCRIPTION
**Pull request by Madhan-SWE**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Rebase the code with upstream kubernetes-sigs/ibm-powervs-block-csi-driver

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by mkumatag** [comment]
@Madhan-SWE I see image build is failing, you may need to update the vendors

**Comment by Madhan-SWE** [comment]
@mkumatag , We don't have vendor directory in the upstream.
Can I fork upstream repo into my account and create a private branch, add vendor directory and raise PR from there?
or how this can be handled?

**Comment by mkumatag** [comment]
> @mkumatag , We don't have vendor directory in the upstream.
> Can I fork upstream repo into my account and create a private branch, add vendor directory and raise PR from there?
> or how this can be handled?

Submitting a PR from your repo will be a better idea

**Comment by Madhan-SWE** [comment]
Closing the PR as the checks were failing.

**Pull request closed without merging**
