### PR TITLE
MULTIARCH-4022: Rebase with upstream: v0.5.1 changes

### PR DESCRIPTION
**Pull request by yussufsh**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
Steps followed:
```
# Remote upstream: git@github.com:kubernetes-sigs/ibm-powervs-block-csi-driver.git
git merge upstream/main
```

**Release note**:
```
none
```

### CODE REVIEW

**Comment by Karthik-K-N** [comment]
Please do update the description with steps followed for rebase, It may help in future.

**Comment by yussufsh** [comment]
> Please do update the description with steps followed for rebase, It may help in future.

Added.

**Comment by yussufsh** [comment]
@jaypoulz are you able to add `acknowledge-critical-fixes-only` lable?

**Pull request merged**
